Update dependencies
Mainly to update html-minifier because its old version fails with
`Uncaught Error: Cannot find module './htmlparser'`

https://github.com/kangax/html-minifier/issues?q=is%3Aissue+Cannot+find+module+%27.%2Fhtmlparser%27+is%3Aclosed